---
apiVersion: v1
kind: Pod
metadata:
  name: stormstar
  namespace: infra
  annotations:
    vkube.io/network: gt
    vkube.io/image-policy: always
spec:
  restartPolicy: Always
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: stormstar-data
  containers:
    - name: stormstar
      image: 192.168.200.3:5000/stormstar:edge
      startupProbe:
        httpGet:
          path: /api/v1/health
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 3
        failureThreshold: 10
      livenessProbe:
        httpGet:
          path: /api/v1/health
          port: 80
        periodSeconds: 30
        failureThreshold: 3
      volumeMounts:
        - name: data
          mountPath: /data
